pipeline {
    agent any

    stages {
        stage('Checkout') {
            steps {
                sh 'ls'
                sh 'chmod +x ./cosmos_django/jenkins_scripts/checkout.sh'
            }
        }
        stage('Test') {
            steps {
                echo 'Tesdtfing..'
            }
        }
        stage('Deploy') {
            steps {
                echo 'Deploying....'
            }
        }
    }
}