/* Allergy Action action_types */
export const REQUEST_ADD_ALLERGY = 'REQUEST_ADD_ALLERGY';
export const RECEIVE_ADD_ALLERGY = 'RECEIVE_ADD_ALLERGY';
export const FAILURE_ADD_ALLERGY = 'FAILURE_ADD_ALLERGY';

export const REQUEST_UPDATE_ALLERGY = 'REQUEST_UPDATE_ALLERGY';
export const RECEIVE_UPDATE_ALLERGY = 'RECEIVE_UPDATE_ALLERGY';
export const FAILURE_UPDATE_ALLERGY = 'FAILURE_UPDATE_ALLERGY';

export const REQUEST_DELETE_ALLERGY = 'REQUEST_DELETE_ALLERGY';
export const RECEIVE_DELETE_ALLERGY = 'RECEIVE_DELETE_ALLERGY';
export const FAILURE_DELETE_ALLERGY = 'FAILURE_DELETE_ALLERGY';
