/* Vaccination Action Types */
export const REQUEST_ADD_VACCINATION = 'REQUEST_ADD_VACCINATION';
export const RECEIVE_ADD_VACCINATION = 'RECEIVE_ADD_VACCINATION';
export const FAILURE_ADD_VACCINATION = 'FAILURE_ADD_VACCINATION';

export const REQUEST_UPDATE_VACCINATION = 'REQUEST_UPDATE_VACCINATION';
export const RECEIVE_UPDATE_VACCINATION = 'RECEIVE_UPDATE_VACCINATION';
export const FAILURE_UPDATE_VACCINATION = 'FAILURE_UPDATE_VACCINATION';

export const REQUEST_DELETE_VACCINATION = 'REQUEST_DELETE_VACCINATION';
export const RECEIVE_DELETE_VACCINATION = 'RECEIVE_DELETE_VACCINATION';
export const FAILURE_DELETE_VACCINATION = 'FAILURE_DELETE_VACCINATION';
