/* User */
export const REQUEST_GET_USER = 'REQUEST_GET_USER';
export const RECEIVE_GET_USER = 'RECEIVE_GET_USER';
export const FAILURE_GET_USER = 'FAILURE_GET_USER';

export const REQUEST_UPDATE_USER = 'REQUEST_UPDATE_USER';
export const RECEIVE_UPDATE_USER = 'RECEIVE_UPDATE_USER';
export const FAILURE_UPDATE_USER = 'FAILURE_UPDATE_USER';

/* Encounter */
export const REQUEST_ADD_ENCOUNTER = 'REQUEST_ADD_ENCOUNTER';
export const RECEIVE_ADD_ENCOUNTER = 'RECEIVE_ADD_ENCOUNTER';
export const FAILURE_ADD_ENCOUNTER = 'FAILURE_ADD_ENCOUNTER';

export const REQUEST_UPDATE_ENCOUNTER = 'REQUEST_UPDATE_ENCOUNTER';
export const RECEIVE_UPDATE_ENCOUNTER = 'RECEIVE_UPDATE_ENCOUNTER';
export const FAILURE_UPDATE_ENCOUNTER = 'FAILURE_UPDATE_ENCOUNTER';

export const REQUEST_DELETE_ENCOUNTER = 'REQUEST_DELETE_ENCOUNTER';
export const RECEIVE_DELETE_ENCOUNTER = 'RECEIVE_DELETE_ENCOUNTER';
export const FAILURE_DELETE_ENCOUNTER = 'FAILURE_DELETE_ENCOUNTER';

/* Diagnosis */
export const REQUEST_ADD_DIAGNOSIS = 'REQUEST_ADD_DIAGNOSIS';
export const RECEIVE_ADD_DIAGNOSIS = 'RECEIVE_ADD_DIAGNOSIS';
export const FAILURE_ADD_DIAGNOSIS = 'FAILURE_ADD_DIAGNOSIS';

export const REQUEST_UPDATE_DIAGNOSIS = 'REQUEST_UPDATE_DIAGNOSIS';
export const RECEIVE_UPDATE_DIAGNOSIS = 'RECEIVE_UPDATE_DIAGNOSIS';
export const FAILURE_UPDATE_DIAGNOSIS = 'FAILURE_UPDATE_DIAGNOSIS';

export const REQUEST_DELETE_DIAGNOSIS = 'REQUEST_DELETE_DIAGNOSIS';
export const RECEIVE_DELETE_DIAGNOSIS = 'RECEIVE_DELETE_DIAGNOSIS';
export const FAILURE_DELETE_DIAGNOSIS = 'FAILURE_DELETE_DIAGNOSIS';

/* Medication */
export const REQUEST_ADD_MEDICATION = 'REQUEST_ADD_MEDICATION';
export const RECEIVE_ADD_MEDICATION = 'RECEIVE_ADD_MEDICATION';
export const FAILURE_ADD_MEDICATION = 'FAILURE_ADD_MEDICATION';

export const REQUEST_UPDATE_MEDICATION = 'REQUEST_UPDATE_MEDICATION';
export const RECEIVE_UPDATE_MEDICATION = 'RECEIVE_UPDATE_MEDICATION';
export const FAILURE_UPDATE_MEDICATION = 'FAILURE_UPDATE_MEDICATION';

export const REQUEST_DELETE_MEDICATION = 'REQUEST_DELETE_MEDICATION';
export const RECEIVE_DELETE_MEDICATION = 'RECEIVE_DELETE_MEDICATION';
export const FAILURE_DELETE_MEDICATION = 'FAILURE_DELETE_MEDICATION';

/* Allergy */
export const REQUEST_ADD_ALLERGY = 'REQUEST_ADD_ALLERGY';
export const RECEIVE_ADD_ALLERGY = 'RECEIVE_ADD_ALLERGY';
export const FAILURE_ADD_ALLERGY = 'FAILURE_ADD_ALLERGY';

export const REQUEST_UPDATE_ALLERGY = 'REQUEST_UPDATE_ALLERGY';
export const RECEIVE_UPDATE_ALLERGY = 'RECEIVE_UPDATE_ALLERGY';
export const FAILURE_UPDATE_ALLERGY = 'FAILURE_UPDATE_ALLERGY';

export const REQUEST_DELETE_ALLERGY = 'REQUEST_DELETE_ALLERGY';
export const RECEIVE_DELETE_ALLERGY = 'RECEIVE_DELETE_ALLERGY';
export const FAILURE_DELETE_ALLERGY = 'FAILURE_DELETE_ALLERGY';

/* Vaccination */
export const REQUEST_ADD_VACCINATION = 'REQUEST_ADD_VACCINATION';
export const RECEIVE_ADD_VACCINATION = 'RECEIVE_ADD_VACCINATION';
export const FAILURE_ADD_VACCINATION = 'FAILURE_ADD_VACCINATION';

export const REQUEST_UPDATE_VACCINATION = 'REQUEST_UPDATE_VACCINATION';
export const RECEIVE_UPDATE_VACCINATION = 'RECEIVE_UPDATE_VACCINATION';
export const FAILURE_UPDATE_VACCINATION = 'FAILURE_UPDATE_VACCINATION';

export const REQUEST_DELETE_VACCINATION = 'REQUEST_DELETE_VACCINATION';
export const RECEIVE_DELETE_VACCINATION = 'RECEIVE_DELETE_VACCINATION';
export const FAILURE_DELETE_VACCINATION = 'FAILURE_DELETE_VACCINATION';
