export const REQUEST_GET_USER = 'REQUEST_GET_USER';
export const RECEIVE_GET_USER = 'RECEIVE_GET_USER';
export const FAILURE_GET_USER = 'FAILURE_GET_USER';

export const REQUEST_UPDATE_USER = 'REQUEST_UPDATE_USER';
export const RECEIVE_UPDATE_USER = 'RECEIVE_UPDATE_USER';
export const FAILURE_UPDATE_USER = 'FAILURE_UPDATE_USER';

export const REQUEST_ADD_ENCOUNTER = 'REQUEST_ADD_ENCOUNTER';
export const RECEIVE_ADD_ENCOUNTER = 'RECEIVE_ADD_ENCOUNTER';
export const FAILURE_ADD_ENCOUNTER = 'FAILURE_ADD_ENCOUNTER';

export const REQUEST_UPDATE_ENCOUNTER = 'REQUEST_UPDATE_ENCOUNTER';
export const RECEIVE_UPDATE_ENCOUNTER = 'RECEIVE_UPDATE_ENCOUNTER';
export const FAILURE_UPDATE_ENCOUNTER = 'FAILURE_UPDATE_ENCOUNTER';
