# Generated by Django 3.0.6 on 2020-05-30 02:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='email',
            field=models.EmailField(max_length=60, unique=True, validators=[django.core.validators.MinLengthValidator(1)]),
        ),
    ]
