# Generated by Django 3.0.6 on 2020-06-06 03:57

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20200530_0250'),
    ]

    operations = [
        migrations.CreateModel(
            name='PatientProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(default=None, max_length=60, validators=[django.core.validators.MinLengthValidator(1)])),
                ('last_name', models.CharField(default=None, max_length=60, validators=[django.core.validators.MinLengthValidator(1)])),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='profile_pictures/')),
                ('account', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='patient_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Visit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visit_type', models.CharField(choices=[('physical', 'Physical'), ('vaccination', 'Vaccination'), ('illness', 'Illness')], max_length=60)),
                ('note', models.CharField(default=None, max_length=1000)),
                ('patient_profile', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='visits', to='account.PatientProfile')),
            ],
        ),
    ]
