# Generated by Django 3.0.6 on 2020-06-08 04:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_patientprofile_visit'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vaccination',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('patient_profile', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vaccinations', to='account.PatientProfile')),
            ],
        ),
        migrations.CreateModel(
            name='Medication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('patient_profile', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='medications', to='account.PatientProfile')),
            ],
        ),
    ]
