# Generated by Django 3.0.6 on 2020-06-09 04:17

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_patientprofile_date_of_birth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientprofile',
            name='date_of_birth',
            field=models.DateField(default=datetime.datetime(2020, 6, 9, 4, 17, 19, 224342, tzinfo=utc)),
        ),
    ]
