# Generated by Django 3.0.6 on 2020-06-28 23:28

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_auto_20200628_0459'),
    ]

    operations = [
        migrations.AddField(
            model_name='encounter',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='encounter',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
