# Generated by Django 3.0.6 on 2020-06-30 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_encounter_significance_band'),
    ]

    operations = [
        migrations.AlterField(
            model_name='encounter',
            name='significance_band',
            field=models.CharField(choices=[('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], default='low', max_length=60),
        ),
    ]
