# Generated by Django 3.0.6 on 2020-07-02 22:47

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_diagnosis'),
    ]

    operations = [
        migrations.AddField(
            model_name='diagnosis',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
