# Generated by Django 3.0.6 on 2020-07-03 03:34

import annoying.fields
from django.db import migrations
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_auto_20200703_0326'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diagnosis',
            name='significance',
            field=annoying.fields.AutoOneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='significance', to='main.Significance'),
        ),
    ]
