# Generated by Django 3.0.6 on 2020-07-03 18:28

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_allergy'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vaccination',
            options={'ordering': ('-created_at',)},
        ),
        migrations.AddField(
            model_name='vaccination',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vaccination',
            name='description',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='vaccination',
            name='significance_group',
            field=models.CharField(choices=[('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], default='low', max_length=60),
        ),
        migrations.AddField(
            model_name='vaccination',
            name='significance_score',
            field=models.IntegerField(default=1),
        ),
    ]
