/* Diagnosis Action Types */
export const REQUEST_ADD_DIAGNOSIS = 'REQUEST_ADD_DIAGNOSIS';
export const RECEIVE_ADD_DIAGNOSIS = 'RECEIVE_ADD_DIAGNOSIS';
export const FAILURE_ADD_DIAGNOSIS = 'FAILURE_ADD_DIAGNOSIS';

export const REQUEST_UPDATE_DIAGNOSIS = 'REQUEST_UPDATE_DIAGNOSIS';
export const RECEIVE_UPDATE_DIAGNOSIS = 'RECEIVE_UPDATE_DIAGNOSIS';
export const FAILURE_UPDATE_DIAGNOSIS = 'FAILURE_UPDATE_DIAGNOSIS';

export const REQUEST_DELETE_DIAGNOSIS = 'REQUEST_DELETE_DIAGNOSIS';
export const RECEIVE_DELETE_DIAGNOSIS = 'RECEIVE_DELETE_DIAGNOSIS';
export const FAILURE_DELETE_DIAGNOSIS = 'FAILURE_DELETE_DIAGNOSIS';
