/* Encounter Action Types */
export const REQUEST_ADD_ENCOUNTER = 'REQUEST_ADD_ENCOUNTER';
export const RECEIVE_ADD_ENCOUNTER = 'RECEIVE_ADD_ENCOUNTER';
export const FAILURE_ADD_ENCOUNTER = 'FAILURE_ADD_ENCOUNTER';

export const REQUEST_UPDATE_ENCOUNTER = 'REQUEST_UPDATE_ENCOUNTER';
export const RECEIVE_UPDATE_ENCOUNTER = 'RECEIVE_UPDATE_ENCOUNTER';
export const FAILURE_UPDATE_ENCOUNTER = 'FAILURE_UPDATE_ENCOUNTER';

export const REQUEST_DELETE_ENCOUNTER = 'REQUEST_DELETE_ENCOUNTER';
export const RECEIVE_DELETE_ENCOUNTER = 'RECEIVE_DELETE_ENCOUNTER';
export const FAILURE_DELETE_ENCOUNTER = 'FAILURE_DELETE_ENCOUNTER';
