/* Medication Action Types */
export const REQUEST_ADD_MEDICATION = 'REQUEST_ADD_MEDICATION';
export const RECEIVE_ADD_MEDICATION = 'RECEIVE_ADD_MEDICATION';
export const FAILURE_ADD_MEDICATION = 'FAILURE_ADD_MEDICATION';

export const REQUEST_UPDATE_MEDICATION = 'REQUEST_UPDATE_MEDICATION';
export const RECEIVE_UPDATE_MEDICATION = 'RECEIVE_UPDATE_MEDICATION';
export const FAILURE_UPDATE_MEDICATION = 'FAILURE_UPDATE_MEDICATION';

export const REQUEST_DELETE_MEDICATION = 'REQUEST_DELETE_MEDICATION';
export const RECEIVE_DELETE_MEDICATION = 'RECEIVE_DELETE_MEDICATION';
export const FAILURE_DELETE_MEDICATION = 'FAILURE_DELETE_MEDICATION';
