# Generated by Django 3.0.6 on 2020-05-30 02:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinical', '0002_auto_20200527_0018'),
    ]

    operations = [
        migrations.AlterField(
            model_name='encounter',
            name='note',
            field=models.CharField(default=None, max_length=1000, validators=[django.core.validators.MinLengthValidator(4)]),
        ),
        migrations.AlterField(
            model_name='patientprofile',
            name='first_name',
            field=models.CharField(default=None, max_length=60, validators=[django.core.validators.MinLengthValidator(1)]),
        ),
        migrations.AlterField(
            model_name='patientprofile',
            name='last_name',
            field=models.CharField(default=None, max_length=60, validators=[django.core.validators.MinLengthValidator(1)]),
        ),
    ]
