# Generated by Django 3.0.6 on 2020-05-31 02:54

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clinical', '0003_auto_20200530_0250'),
    ]

    operations = [
        migrations.CreateModel(
            name='Visit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visit_type', models.CharField(choices=[('physical', 'Physical'), ('vaccination', 'Vaccination'), ('illness', 'Illness')], max_length=60)),
                ('note', models.CharField(default=None, max_length=1000, validators=[django.core.validators.MinLengthValidator(4)])),
                ('patient_profile', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='clinical.PatientProfile')),
            ],
        ),
        migrations.DeleteModel(
            name='Encounter',
        ),
    ]
