# Generated by Django 3.0.6 on 2020-06-02 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinical', '0006_auto_20200602_0301'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientprofile',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pictures/'),
        ),
    ]
