# Generated by Django 3.0.6 on 2020-06-24 01:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20200624_0056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='encounter',
            name='patient_profile',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='encounters', to='main.PatientProfile'),
        ),
    ]
