# Generated by Django 3.0.6 on 2020-06-28 00:06

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_patientprofile_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientprofile',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, default='', max_length=128, null=True, region=None),
        ),
    ]
