# Generated by Django 3.0.6 on 2020-06-28 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20200628_0421'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientprofile',
            name='ethnicity',
            field=models.CharField(blank=True, default='', max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='patientprofile',
            name='race',
            field=models.CharField(blank=True, default='', max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='patientprofile',
            name='religion',
            field=models.CharField(blank=True, default='', max_length=60, null=True),
        ),
    ]
