# Generated by Django 3.0.6 on 2020-06-28 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20200628_0437'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientprofile',
            name='insurance',
            field=models.CharField(blank=True, default='', max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='patientprofile',
            name='pharmacy',
            field=models.CharField(blank=True, default='', max_length=60, null=True),
        ),
    ]
