# Generated by Django 3.0.6 on 2020-06-30 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_auto_20200628_2328'),
    ]

    operations = [
        migrations.AddField(
            model_name='encounter',
            name='significance_band',
            field=models.CharField(choices=[('high', 'High'), ('low', 'Medium'), ('low', 'Low')], default='low', max_length=60),
        ),
    ]
