# Generated by Django 3.0.6 on 2020-06-30 16:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_auto_20200630_0137'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='encounter',
            options={'ordering': ('-created_at',)},
        ),
    ]
