# Generated by Django 3.0.6 on 2020-07-02 21:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_auto_20200630_1609'),
    ]

    operations = [
        migrations.CreateModel(
            name='Diagnosis',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=1000)),
                ('patient_profile', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='diagnoses', to='main.PatientProfile')),
            ],
        ),
    ]
