# Generated by Django 3.0.6 on 2020-07-03 03:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_diagnosis_created_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='Significance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(default=1)),
                ('group', models.CharField(choices=[('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], default='low', max_length=60)),
            ],
        ),
        migrations.AddField(
            model_name='diagnosis',
            name='significance',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='significance', to='main.Significance'),
        ),
    ]
