# Generated by Django 3.0.6 on 2020-07-03 16:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_auto_20200703_0334'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='encounter',
            name='significance_band',
        ),
    ]
