# Generated by Django 3.0.6 on 2020-07-12 02:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0023_providerprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patientprofile',
            name='phone_number',
        ),
    ]
